Vagrant.configure("2") do |config|

	config.vm.box = "debian/bullseye64"
	config.vm.provider "virtualbox" do |vb|
	  vb.name = "debian-client"
	  vb.memory = "2048"
	  vb.name = "gde-client"
	  vb.cpus = 2
	  vb.customize ["modifyvm", :id, "--nic2", "intnet"]
	  vb.customize ["modifyvm", :id, "--intnet2", "demo_network"]
	end

	config.vm.define "demo" do |demo|
		demo.vm.hostname = "gde-client"
		config.vm.network "private_network", ip: "192.168.10.20", virtualbox__intnet: "demo_network", auto_config: true, adapter: 2

		config.vm.network "forwarded_port", guest: 22, host: 2220
	end
		config.vm.provision "shell", inline: <<-SHELL
	  # Update packages
	  sudo apt-get update
	SHELL

  end